# """added meta_data column

# Revision ID: 04fc9c8562f6
# Revises: fcb52b6816bb
# Create Date: 2026-03-18 10:14:20.427116
# """

# from typing import Sequence, Union

# from alembic import op
# import sqlalchemy as sa
# from sqlalchemy.dialects import mysql

# # revision identifiers, used by Alembic.
# revision: str = '04fc9c8562f6'
# down_revision: Union[str, None] = 'fcb52b6816bb'
# branch_labels: Union[str, Sequence[str], None] = None
# depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_index('ix_messages_session_id', table_name='messages')
#     op.drop_table('messages')
#     op.add_column('tools_messages', sa.Column('meta_data', sa.JSON(), nullable=True))
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_column('tools_messages', 'meta_data')
#     op.create_table('messages',
#     sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('session_id', mysql.INTEGER(), autoincrement=False, nullable=False),
#     sa.Column('role', mysql.ENUM('user', 'assistant', 'system'), nullable=False),
#     sa.Column('content', mysql.TEXT(), nullable=False),
#     sa.Column('timestamp', mysql.DATETIME(), nullable=False),
#     sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], name='messages_ibfk_1', ondelete='CASCADE'),
#     sa.PrimaryKeyConstraint('id'),
#     mysql_collate='utf8mb4_0900_ai_ci',
#     mysql_default_charset='utf8mb4',
#     mysql_engine='InnoDB'
#     )
#     op.create_index('ix_messages_session_id', 'messages', ['session_id'], unique=False)
#     # ### end Alembic commands ###
"""added meta_data column

Revision ID: 04fc9c8562f6
Revises: fcb52b6816bb
Create Date: 2026-03-18 10:14:20.427116
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '04fc9c8562f6'
down_revision: Union[str, None] = 'fcb52b6816bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ✅ ONLY add the new column
    op.add_column(
        'tools_messages',
        sa.Column('meta_data', sa.JSON(), nullable=True)
    )


def downgrade() -> None:
    # ✅ ONLY remove the column
    op.drop_column('tools_messages', 'meta_data')