"""add_meta_data_to_agents_messages

Revision ID: 0f8b73ece069
Revises: 04fc9c8562f6
Create Date: 2026-03-24 10:02:06.298373
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
"""add_meta_data_to_agents_messages

Revision ID: 0f8b73ece069
Revises: 04fc9c8562f6
Create Date: 2026-03-24 10:02:06.298373
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0f8b73ece069'
down_revision: Union[str, None] = '737f71f0959c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents_messages', sa.Column('meta_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents_messages', 'meta_data')
    # ### end Alembic commands ###
