"""Add User personalization and UI fields

Revision ID: 737f71f0959c
Revises: 04fc9c8562f6
Create Date: 2026-03-24 21:51:54.167451
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '737f71f0959c'
down_revision: Union[str, None] = '04fc9c8562f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nickname', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('occupation', sa.String(length=150), nullable=True))
    op.add_column('users', sa.Column('about_me', sa.String(length=1000), nullable=True))
    op.add_column('users', sa.Column('custom_instructions', sa.String(length=2000), nullable=True))
    op.add_column('users', sa.Column('appearance', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('accent_color', sa.String(length=30), nullable=False))
    op.add_column('users', sa.Column('language', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'language')
    op.drop_column('users', 'accent_color')
    op.drop_column('users', 'appearance')
    op.drop_column('users', 'custom_instructions')
    op.drop_column('users', 'about_me')
    op.drop_column('users', 'occupation')
    op.drop_column('users', 'nickname')
    # ### end Alembic commands ###
