"""add personalization columns to users

Revision ID: cb1527610725
Revises: 0f8b73ece069
Create Date: 2026-03-24 16:06:55.390812
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb1527610725'
down_revision: Union[str, None] = '0f8b73ece069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Redundant with 737f71f0959c - moved to single chain
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
