"""add meta_data to tools_messages

Revision ID: fcb52b6816bb
Revises: d3504080575c
Create Date: 2026-03-17 10:20:00.641430
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fcb52b6816bb'
down_revision: Union[str, None] = 'd3504080575c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools_messages', sa.Column('meta_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tools_messages', 'meta_data')
    # ### end Alembic commands ###
