"""
Report Agent - Formats the final response for the user.
"""

from __future__ import annotations
import logging

logger = logging.getLogger(__name__)

class ReportAgent:
    def format_final_report(self, optimized_resume: str, match_data: str, suggestions: str) -> str:
        """Combine all components into a structured final response."""
        return f"""
# 🚀 Resume Optimization Analysis

## 📊 Skill Match & Market Alignment
{match_data}

## 💡 Strategic Improvement Suggestions
{suggestions}

---

# 📄 Optimized Resume Content
> **Note:** Copy the content below and paste it into your preferred resume template.

{optimized_resume}

---
*Generated by Campus AI Resume Agent*
"""
